---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: mock-av-scanner
spec:
  description: >-
    This is a dummy task that emulates an anti-virus scanner task. Its sole purpose is to facilitate
    testing.
  params:
    - name: TEST_OUTPUT
      description: The value to of the TEST_OUTPUT commit result.
  results:
    - name: TEST_OUTPUT
      description: The summary scanner output.
  steps:
    - name: scan
      image: registry.access.redhat.com/ubi9:latest
      env:
      - name: TEST_OUTPUT
        value: "$(params.TEST_OUTPUT)"
      script: |
        #!/usr/bin/env sh
        set -euo pipefail

        echo -n "${TEST_OUTPUT}" > "$(results.TEST_OUTPUT.path)"
