apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
  creationTimestamp: "2024-01-08T19:18:07Z"
  finalizers:
  - chains.tekton.dev/pipelinerun
  generation: 1
  labels:
    tekton.dev/pipeline: simple-build
  name: simple-build-run-70f8eb138a
  namespace: default
  resourceVersion: "4533"
  uid: 1b566f85-2c13-4714-b7ba-18934fc7cc1c
spec:
  params:
  - name: IMAGE_DIGEST
    value: sha256:29b9b7a7d9a4acc317f8fec892d072e482cbb9b03025d8d078b49872a11d2d9a
  - name: IMAGE_URL
    value: quay.io/lucarval/test-policies-chains
  - name: TEST_OUTPUT
    value: missing
  - name: commit
    value: 18304972d3e4a7621b899da8181b563820bb7861
  - name: committer-date
    value: "1704741487"
  - name: url
    value: gitspam.spam/spam/spam
  pipelineRef:
    name: simple-build
  taskRunTemplate:
    serviceAccountName: default
  timeouts:
    pipeline: 1h0m0s
status:
  childReferences:
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-70f8eb138a-git-clone
    pipelineTaskName: git-clone
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-70f8eb138a-scan
    pipelineTaskName: scan
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-70f8eb138a-av-scan
    pipelineTaskName: av-scan
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-70f8eb138a-build
    pipelineTaskName: build
  completionTime: "2024-01-08T19:18:21Z"
  conditions:
  - lastTransitionTime: "2024-01-08T19:18:21Z"
    message: 'Tasks Completed: 4 (Failed: 0, Cancelled 0), Skipped: 0'
    reason: Succeeded
    status: "True"
    type: Succeeded
  pipelineSpec:
    params:
    - name: commit
      type: string
    - name: url
      type: string
    - name: committer-date
      type: string
    - name: IMAGE_URL
      type: string
    - name: IMAGE_DIGEST
      type: string
    - name: TEST_OUTPUT
      type: string
    results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.build.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.build.results.IMAGE_DIGEST)
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.git-clone.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.git-clone.results.commit)
    tasks:
    - name: git-clone
      params:
      - name: commit
        value: 18304972d3e4a7621b899da8181b563820bb7861
      - name: url
        value: gitspam.spam/spam/spam
      - name: committer-date
        value: "1704741487"
      taskRef:
        kind: Task
        params:
        - name: url
          value: https://github.com/enterprise-contract/hacks.git
        - name: revision
          value: 4fceb2416020011e794105f113a3913ef659c8ee
        - name: pathInRepo
          value: provenance/task/mock-git-clone.yaml
        resolver: git
    - name: scan
      params:
      - name: TEST_OUTPUT
        value: missing
      runAfter:
      - git-clone
      taskSpec:
        description: This is a dummy task that emulates a task that scans source code.
          Its sole purpose is to facilitate testing.
        metadata: {}
        params:
        - description: The value to of the TEST_OUTPUT commit result.
          name: TEST_OUTPUT
          type: string
        results:
        - description: The summary scanner output.
          name: TEST_OUTPUT
          type: string
        spec: null
        steps:
        - computeResources: {}
          env:
          - name: TEST_OUTPUT
            value: missing
          image: registry.access.redhat.com/ubi9:latest
          name: scan
          script: |
            #!/usr/bin/env sh
            set -euo pipefail

            echo -n "${TEST_OUTPUT}" > "$(results.TEST_OUTPUT.path)"
    - name: av-scan
      params:
      - name: TEST_OUTPUT
        value: missing
      runAfter:
      - git-clone
      taskRef:
        kind: Task
        name: mock-av-scanner
    - name: build
      params:
      - name: IMAGE_URL
        value: quay.io/lucarval/test-policies-chains
      - name: IMAGE_DIGEST
        value: sha256:29b9b7a7d9a4acc317f8fec892d072e482cbb9b03025d8d078b49872a11d2d9a
      runAfter:
      - scan
      taskRef:
        kind: Task
        params:
        - name: bundle
          value: quay.io/lucarval/test-policies-chains@sha256:b766741b8b3e135e4e31281aa4b25899e951798b5f213cc4a5360d01eb9b6880
        - name: name
          value: mock-build
        - name: kind
          value: task
        resolver: bundles
  provenance:
    featureFlags:
      AwaitSidecarReadiness: true
      Coschedule: workspaces
      DisableAffinityAssistant: false
      DisableCredsInit: false
      EnableAPIFields: alpha
      EnableCELInWhenExpression: false
      EnableKeepPodOnCancel: false
      EnableParamEnum: false
      EnableProvenanceInStatus: true
      EnableStepActions: false
      EnableTektonOCIBundles: true
      EnforceNonfalsifiability: none
      MaxResultSize: 4096
      RequireGitSSHSecretKnownHosts: false
      ResultExtractionMethod: termination-message
      RunningInEnvWithInjectedSidecars: true
      ScopeWhenExpressionsToTask: false
      SendCloudEventsForRuns: false
      SetSecurityContext: false
      VerificationNoMatchPolicy: ignore
  results:
  - name: IMAGE_URL
    value: quay.io/lucarval/test-policies-chains
  - name: IMAGE_DIGEST
    value: sha256:29b9b7a7d9a4acc317f8fec892d072e482cbb9b03025d8d078b49872a11d2d9a
  - name: CHAINS-GIT_URL
    value: gitspam.spam/spam/spam
  - name: CHAINS-GIT_COMMIT
    value: 18304972d3e4a7621b899da8181b563820bb7861
  startTime: "2024-01-08T19:18:07Z"
