---
removeParams:
  - gitInitImage
  - deleteExisting
  - subdirectory
addEnvironment:
  - name: CHECKOUT_DIR
    value: /var/source
add:
  - create
removeWorkspaces:
  - output
description: The git-clone-oci-ta Task will clone a repo from the provided url and store it as a trusted
    artifact in the provided OCI repository.
workdirName: source
