apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
  creationTimestamp: "2024-01-08T19:16:38Z"
  finalizers:
  - chains.tekton.dev/pipelinerun
  generation: 1
  labels:
    tekton.dev/pipeline: simple-build-run-5a78d8baba
  name: simple-build-run-5a78d8baba
  namespace: default
  resourceVersion: "3598"
  uid: 93963d53-84f1-4110-8b3b-bdf2515306fe
spec:
  params:
  - name: IMAGE_DIGEST
    value: sha256:f4c4be50b5c018d93a88a662870b2ee566f16807c307eb881c5eea7c2dc70f60
  - name: IMAGE_URL
    value: quay.io/lucarval/test-policies-chains
  - name: TEST_OUTPUT
    value: missing
  - name: commit
    value: 7d0c0a69d2e3e7940a364c46b07591e371e11b38
  - name: committer-date
    value: "1704741397"
  - name: url
    value: gitspam.spam/spam/spam
  pipelineSpec:
    params:
    - name: commit
      type: string
    - name: url
      type: string
    - name: committer-date
      type: string
    - name: IMAGE_URL
      type: string
    - name: IMAGE_DIGEST
      type: string
    - name: TEST_OUTPUT
      type: string
    results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.build.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.build.results.IMAGE_DIGEST)
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.git-clone.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.git-clone.results.commit)
    tasks:
    - name: git-clone
      params:
      - name: commit
        value: $(params.commit)
      - name: url
        value: $(params.url)
      - name: committer-date
        value: $(params.committer-date)
      taskRef:
        kind: Task
        params:
        - name: url
          value: https://github.com/enterprise-contract/hacks.git
        - name: revision
          value: 4fceb2416020011e794105f113a3913ef659c8ee
        - name: pathInRepo
          value: provenance/task/mock-git-clone.yaml
        resolver: git
    - name: scan
      params:
      - name: TEST_OUTPUT
        value: $(params.TEST_OUTPUT)
      runAfter:
      - git-clone
      taskSpec:
        description: This is a dummy task that emulates a task that scans source code.
          Its sole purpose is to facilitate testing.
        metadata: {}
        params:
        - description: The value to of the TEST_OUTPUT commit result.
          name: TEST_OUTPUT
          type: string
        results:
        - description: The summary scanner output.
          name: TEST_OUTPUT
          type: string
        spec: null
        steps:
        - computeResources: {}
          env:
          - name: TEST_OUTPUT
            value: $(params.TEST_OUTPUT)
          image: registry.access.redhat.com/ubi9:latest
          name: scan
          script: |
            #!/usr/bin/env sh
            set -euo pipefail

            echo -n "${TEST_OUTPUT}" > "$(results.TEST_OUTPUT.path)"
    - name: av-scan
      params:
      - name: TEST_OUTPUT
        value: $(params.TEST_OUTPUT)
      runAfter:
      - git-clone
      taskRef:
        kind: Task
        name: mock-av-scanner
    - name: build
      params:
      - name: IMAGE_URL
        value: $(params.IMAGE_URL)
      - name: IMAGE_DIGEST
        value: $(params.IMAGE_DIGEST)
      runAfter:
      - scan
      taskRef:
        kind: Task
        params:
        - name: bundle
          value: quay.io/lucarval/test-policies-chains@sha256:5b65acfc5a31c6f88112c22e119a30d54230ca2d85ff079cdab9feeeaa58f964
        - name: name
          value: mock-build
        - name: kind
          value: task
        resolver: bundles
  taskRunTemplate:
    serviceAccountName: default
  timeouts:
    pipeline: 1h0m0s
status:
  childReferences:
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-5a78d8baba-git-clone
    pipelineTaskName: git-clone
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-5a78d8baba-scan
    pipelineTaskName: scan
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-5a78d8baba-av-scan
    pipelineTaskName: av-scan
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-5a78d8baba-build
    pipelineTaskName: build
  completionTime: "2024-01-08T19:16:56Z"
  conditions:
  - lastTransitionTime: "2024-01-08T19:16:56Z"
    message: 'Tasks Completed: 4 (Failed: 0, Cancelled 0), Skipped: 0'
    reason: Succeeded
    status: "True"
    type: Succeeded
  pipelineSpec:
    params:
    - name: commit
      type: string
    - name: url
      type: string
    - name: committer-date
      type: string
    - name: IMAGE_URL
      type: string
    - name: IMAGE_DIGEST
      type: string
    - name: TEST_OUTPUT
      type: string
    results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.build.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.build.results.IMAGE_DIGEST)
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.git-clone.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.git-clone.results.commit)
    tasks:
    - name: git-clone
      params:
      - name: commit
        value: 7d0c0a69d2e3e7940a364c46b07591e371e11b38
      - name: url
        value: gitspam.spam/spam/spam
      - name: committer-date
        value: "1704741397"
      taskRef:
        kind: Task
        params:
        - name: url
          value: https://github.com/enterprise-contract/hacks.git
        - name: revision
          value: 4fceb2416020011e794105f113a3913ef659c8ee
        - name: pathInRepo
          value: provenance/task/mock-git-clone.yaml
        resolver: git
    - name: scan
      params:
      - name: TEST_OUTPUT
        value: missing
      runAfter:
      - git-clone
      taskSpec:
        description: This is a dummy task that emulates a task that scans source code.
          Its sole purpose is to facilitate testing.
        metadata: {}
        params:
        - description: The value to of the TEST_OUTPUT commit result.
          name: TEST_OUTPUT
          type: string
        results:
        - description: The summary scanner output.
          name: TEST_OUTPUT
          type: string
        spec: null
        steps:
        - computeResources: {}
          env:
          - name: TEST_OUTPUT
            value: missing
          image: registry.access.redhat.com/ubi9:latest
          name: scan
          script: |
            #!/usr/bin/env sh
            set -euo pipefail

            echo -n "${TEST_OUTPUT}" > "$(results.TEST_OUTPUT.path)"
    - name: av-scan
      params:
      - name: TEST_OUTPUT
        value: missing
      runAfter:
      - git-clone
      taskRef:
        kind: Task
        name: mock-av-scanner
    - name: build
      params:
      - name: IMAGE_URL
        value: quay.io/lucarval/test-policies-chains
      - name: IMAGE_DIGEST
        value: sha256:f4c4be50b5c018d93a88a662870b2ee566f16807c307eb881c5eea7c2dc70f60
      runAfter:
      - scan
      taskRef:
        kind: Task
        params:
        - name: bundle
          value: quay.io/lucarval/test-policies-chains@sha256:5b65acfc5a31c6f88112c22e119a30d54230ca2d85ff079cdab9feeeaa58f964
        - name: name
          value: mock-build
        - name: kind
          value: task
        resolver: bundles
  provenance:
    featureFlags:
      AwaitSidecarReadiness: true
      Coschedule: workspaces
      DisableAffinityAssistant: false
      DisableCredsInit: false
      EnableAPIFields: alpha
      EnableCELInWhenExpression: false
      EnableKeepPodOnCancel: false
      EnableParamEnum: false
      EnableProvenanceInStatus: true
      EnableStepActions: false
      EnableTektonOCIBundles: true
      EnforceNonfalsifiability: none
      MaxResultSize: 4096
      RequireGitSSHSecretKnownHosts: false
      ResultExtractionMethod: termination-message
      RunningInEnvWithInjectedSidecars: true
      ScopeWhenExpressionsToTask: false
      SendCloudEventsForRuns: false
      SetSecurityContext: false
      VerificationNoMatchPolicy: ignore
  results:
  - name: IMAGE_URL
    value: quay.io/lucarval/test-policies-chains
  - name: IMAGE_DIGEST
    value: sha256:f4c4be50b5c018d93a88a662870b2ee566f16807c307eb881c5eea7c2dc70f60
  - name: CHAINS-GIT_URL
    value: gitspam.spam/spam/spam
  - name: CHAINS-GIT_COMMIT
    value: 7d0c0a69d2e3e7940a364c46b07591e371e11b38
  startTime: "2024-01-08T19:16:38Z"
