apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
  creationTimestamp: "2023-10-17T16:10:14Z"
  finalizers:
  - chains.tekton.dev/pipelinerun
  generation: 1
  labels:
    tekton.dev/pipeline: simple-build-run-82a058113c
  name: simple-build-run-82a058113c
  namespace: default
  resourceVersion: "1884"
  uid: 3db243c8-57cc-47ea-847d-93a1e17bbe79
spec:
  params:
  - name: IMAGE_DIGEST
    value: sha256:7cd8d408a6184e0923cef34cc6a8b2f012c9faef337272677adf093e3ea73c2a
  - name: IMAGE_URL
    value: quay.io/lucarval/test-policies-chains
  - name: TEST_OUTPUT
    value: missing
  - name: commit
    value: fc98226c7a4206e9b4e9fe99172ddc3a5ae6edfa
  - name: committer-date
    value: "1697559014"
  - name: url
    value: gitspam.spam/spam/spam
  pipelineSpec:
    params:
    - name: commit
      type: string
    - name: url
      type: string
    - name: committer-date
      type: string
    - name: IMAGE_URL
      type: string
    - name: IMAGE_DIGEST
      type: string
    - name: TEST_OUTPUT
      type: string
    results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.build.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.build.results.IMAGE_DIGEST)
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.git-clone.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.git-clone.results.commit)
    tasks:
    - name: git-clone
      params:
      - name: commit
        value: $(params.commit)
      - name: url
        value: $(params.url)
      - name: committer-date
        value: $(params.committer-date)
      taskRef:
        kind: Task
        params:
        - name: url
          value: https://github.com/lcarva/ec-policies.git
        - name: revision
          value: 727f8cae69fdfbae7cf8a44fd5e2055ad9573fb9
        - name: pathInRepo
          value: integration/task/mock-git-clone.yaml
        resolver: git
    - name: scan
      params:
      - name: TEST_OUTPUT
        value: $(params.TEST_OUTPUT)
      runAfter:
      - git-clone
      taskSpec:
        description: This is a dummy task that emulates a task that scans source code.
          Its sole purpose is to facilitate testing.
        metadata: {}
        params:
        - description: The value to of the TEST_OUTPUT commit result.
          name: TEST_OUTPUT
          type: string
        results:
        - description: The summary scanner output.
          name: TEST_OUTPUT
          type: string
        spec: null
        steps:
        - computeResources: {}
          env:
          - name: TEST_OUTPUT
            value: $(params.TEST_OUTPUT)
          image: registry.access.redhat.com/ubi9:latest
          name: scan
          script: |
            #!/usr/bin/env sh
            set -euo pipefail

            echo -n "${TEST_OUTPUT}" > "$(results.TEST_OUTPUT.path)"
    - name: build
      params:
      - name: IMAGE_URL
        value: $(params.IMAGE_URL)
      - name: IMAGE_DIGEST
        value: $(params.IMAGE_DIGEST)
      runAfter:
      - scan
      taskRef:
        kind: Task
        params:
        - name: bundle
          value: quay.io/lucarval/test-policies-chains@sha256:eddc8ae8a13347bd8fdaa1843cc62eac9d3cc12801cd48fe858c087bfba9bd7f
        - name: name
          value: mock-build
        - name: kind
          value: task
        resolver: bundles
  taskRunTemplate:
    serviceAccountName: default
  timeouts:
    pipeline: 1h0m0s
status:
  childReferences:
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-82a058113c-git-clone
    pipelineTaskName: git-clone
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-82a058113c-scan
    pipelineTaskName: scan
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-82a058113c-build
    pipelineTaskName: build
  completionTime: "2023-10-17T16:10:29Z"
  conditions:
  - lastTransitionTime: "2023-10-17T16:10:29Z"
    message: 'Tasks Completed: 3 (Failed: 0, Cancelled 0), Skipped: 0'
    reason: Succeeded
    status: "True"
    type: Succeeded
  pipelineSpec:
    params:
    - name: commit
      type: string
    - name: url
      type: string
    - name: committer-date
      type: string
    - name: IMAGE_URL
      type: string
    - name: IMAGE_DIGEST
      type: string
    - name: TEST_OUTPUT
      type: string
    results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.build.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.build.results.IMAGE_DIGEST)
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.git-clone.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.git-clone.results.commit)
    tasks:
    - name: git-clone
      params:
      - name: commit
        value: fc98226c7a4206e9b4e9fe99172ddc3a5ae6edfa
      - name: url
        value: gitspam.spam/spam/spam
      - name: committer-date
        value: "1697559014"
      taskRef:
        kind: Task
        params:
        - name: url
          value: https://github.com/lcarva/ec-policies.git
        - name: revision
          value: 727f8cae69fdfbae7cf8a44fd5e2055ad9573fb9
        - name: pathInRepo
          value: integration/task/mock-git-clone.yaml
        resolver: git
    - name: scan
      params:
      - name: TEST_OUTPUT
        value: missing
      runAfter:
      - git-clone
      taskSpec:
        description: This is a dummy task that emulates a task that scans source code.
          Its sole purpose is to facilitate testing.
        metadata: {}
        params:
        - description: The value to of the TEST_OUTPUT commit result.
          name: TEST_OUTPUT
          type: string
        results:
        - description: The summary scanner output.
          name: TEST_OUTPUT
          type: string
        spec: null
        steps:
        - computeResources: {}
          env:
          - name: TEST_OUTPUT
            value: missing
          image: registry.access.redhat.com/ubi9:latest
          name: scan
          script: |
            #!/usr/bin/env sh
            set -euo pipefail

            echo -n "${TEST_OUTPUT}" > "$(results.TEST_OUTPUT.path)"
    - name: build
      params:
      - name: IMAGE_URL
        value: quay.io/lucarval/test-policies-chains
      - name: IMAGE_DIGEST
        value: sha256:7cd8d408a6184e0923cef34cc6a8b2f012c9faef337272677adf093e3ea73c2a
      runAfter:
      - scan
      taskRef:
        kind: Task
        params:
        - name: bundle
          value: quay.io/lucarval/test-policies-chains@sha256:eddc8ae8a13347bd8fdaa1843cc62eac9d3cc12801cd48fe858c087bfba9bd7f
        - name: name
          value: mock-build
        - name: kind
          value: task
        resolver: bundles
  provenance:
    featureFlags:
      AwaitSidecarReadiness: true
      Coschedule: workspaces
      DisableAffinityAssistant: false
      DisableCredsInit: false
      EnableAPIFields: beta
      EnableProvenanceInStatus: true
      EnableTektonOCIBundles: false
      EnforceNonfalsifiability: none
      MaxResultSize: 4096
      RequireGitSSHSecretKnownHosts: false
      ResultExtractionMethod: termination-message
      RunningInEnvWithInjectedSidecars: true
      ScopeWhenExpressionsToTask: false
      SendCloudEventsForRuns: false
      SetSecurityContext: false
      VerificationNoMatchPolicy: ignore
  results:
  - name: IMAGE_URL
    value: quay.io/lucarval/test-policies-chains
  - name: IMAGE_DIGEST
    value: sha256:7cd8d408a6184e0923cef34cc6a8b2f012c9faef337272677adf093e3ea73c2a
  - name: CHAINS-GIT_URL
    value: gitspam.spam/spam/spam
  - name: CHAINS-GIT_COMMIT
    value: fc98226c7a4206e9b4e9fe99172ddc3a5ae6edfa
  startTime: "2023-10-17T16:10:14Z"
